# Site settings
title: Labweb360
email: ceweb@nic.br
description: > # this means to ignore newlines until "baseurl:"
  Projeto Labweb360 lançado pelo Centro de Estudos sobre Tecnologias Web (Ceweb.br) com foco em pesquisa e experimentação de tecnologias interativas de realidade virtual e vídeo 360º.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
exclude : ['css', '_sass', 'feed.xml', 'node_modules', ' _build-config.yml', 'gulpfile.js', 'Gruntfile.js', '.DS_Store', 'package.json']
keep_files : ['css', 'js', 'img', 'sass', 'videos']
env : dev
collections :
  galeria:
    output: true
    permalink: /:collection/:path/

